# Generated by Django 4.2.4 on 2023-08-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tipe_donation', models.CharField(max_length=50)),
                ('tipe_user', models.CharField(max_length=50)),
                ('donation', models.BooleanField(default=False)),
            ],
        ),
    ]
