# Generated by Django 4.2.4 on 2023-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_remove_donation_donation_donation_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='tipe_user',
            field=models.CharField(choices=[('asisitente', 'Asistente'), ('especial', 'Invitado especial')], max_length=50),
        ),
    ]
