# Generated by Django 4.2.4 on 2023-09-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_donation_tipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.CharField(default='sebas@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
